---
development:
  cloud_name: tombs
  api_key: '161293998851942'
  api_secret: rRwcMb8J0jWXXeNsDjuCFCqFXf0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: tombs
  api_key: '161293998851942'
  api_secret: rRwcMb8J0jWXXeNsDjuCFCqFXf0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: tombs
  api_key: '161293998851942'
  api_secret: rRwcMb8J0jWXXeNsDjuCFCqFXf0
  enhance_image_tag: true
  static_image_support: false
