---
development:
  cloud_name: tombs
  api_key: '161293998851942'
  api_secret: rRwcMb8J0jWXXeNsDjuCFCqFXf0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["API_KEY"] %>
  api_secret: <%= ENV["API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["API_KEY"] %>
  api_secret: <%= ENV["API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false
